// shared/proto/episode.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: episode.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EpisodeIngestedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EpisodeId     string                 `protobuf:"bytes,1,opt,name=episode_id,json=episodeId,proto3" json:"episode_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	StoragePath   string                 `protobuf:"bytes,3,opt,name=storage_path,json=storagePath,proto3" json:"storage_path,omitempty"`
	Format        string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"` // mcap | hdf5
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EpisodeIngestedEvent) Reset() {
	*x = EpisodeIngestedEvent{}
	mi := &file_episode_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpisodeIngestedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpisodeIngestedEvent) ProtoMessage() {}

func (x *EpisodeIngestedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_episode_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpisodeIngestedEvent.ProtoReflect.Descriptor instead.
func (*EpisodeIngestedEvent) Descriptor() ([]byte, []int) {
	return file_episode_proto_rawDescGZIP(), []int{0}
}

func (x *EpisodeIngestedEvent) GetEpisodeId() string {
	if x != nil {
		return x.EpisodeId
	}
	return ""
}

func (x *EpisodeIngestedEvent) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *EpisodeIngestedEvent) GetStoragePath() string {
	if x != nil {
		return x.StoragePath
	}
	return ""
}

func (x *EpisodeIngestedEvent) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type EpisodeReadyEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EpisodeId     string                 `protobuf:"bytes,1,opt,name=episode_id,json=episodeId,proto3" json:"episode_id,omitempty"`
	QualityScore  float32                `protobuf:"fixed32,2,opt,name=quality_score,json=qualityScore,proto3" json:"quality_score,omitempty"`
	TopicCount    int32                  `protobuf:"varint,3,opt,name=topic_count,json=topicCount,proto3" json:"topic_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EpisodeReadyEvent) Reset() {
	*x = EpisodeReadyEvent{}
	mi := &file_episode_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpisodeReadyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpisodeReadyEvent) ProtoMessage() {}

func (x *EpisodeReadyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_episode_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpisodeReadyEvent.ProtoReflect.Descriptor instead.
func (*EpisodeReadyEvent) Descriptor() ([]byte, []int) {
	return file_episode_proto_rawDescGZIP(), []int{1}
}

func (x *EpisodeReadyEvent) GetEpisodeId() string {
	if x != nil {
		return x.EpisodeId
	}
	return ""
}

func (x *EpisodeReadyEvent) GetQualityScore() float32 {
	if x != nil {
		return x.QualityScore
	}
	return 0
}

func (x *EpisodeReadyEvent) GetTopicCount() int32 {
	if x != nil {
		return x.TopicCount
	}
	return 0
}

var File_episode_proto protoreflect.FileDescriptor

const file_episode_proto_rawDesc = "" +
	"\n" +
	"\repisode.proto\x12\n" +
	"embedai.v1\"\x8f\x01\n" +
	"\x14EpisodeIngestedEvent\x12\x1d\n" +
	"\n" +
	"episode_id\x18\x01 \x01(\tR\tepisodeId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12!\n" +
	"\fstorage_path\x18\x03 \x01(\tR\vstoragePath\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\"x\n" +
	"\x11EpisodeReadyEvent\x12\x1d\n" +
	"\n" +
	"episode_id\x18\x01 \x01(\tR\tepisodeId\x12#\n" +
	"\rquality_score\x18\x02 \x01(\x02R\fqualityScore\x12\x1f\n" +
	"\vtopic_count\x18\x03 \x01(\x05R\n" +
	"topicCountB/Z-github.com/embedai/datahub/shared/proto;protob\x06proto3"

var (
	file_episode_proto_rawDescOnce sync.Once
	file_episode_proto_rawDescData []byte
)

func file_episode_proto_rawDescGZIP() []byte {
	file_episode_proto_rawDescOnce.Do(func() {
		file_episode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_episode_proto_rawDesc), len(file_episode_proto_rawDesc)))
	})
	return file_episode_proto_rawDescData
}

var file_episode_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_episode_proto_goTypes = []any{
	(*EpisodeIngestedEvent)(nil), // 0: embedai.v1.EpisodeIngestedEvent
	(*EpisodeReadyEvent)(nil),    // 1: embedai.v1.EpisodeReadyEvent
}
var file_episode_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_episode_proto_init() }
func file_episode_proto_init() {
	if File_episode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_episode_proto_rawDesc), len(file_episode_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_episode_proto_goTypes,
		DependencyIndexes: file_episode_proto_depIdxs,
		MessageInfos:      file_episode_proto_msgTypes,
	}.Build()
	File_episode_proto = out.File
	file_episode_proto_goTypes = nil
	file_episode_proto_depIdxs = nil
}
