// shared/proto/stream.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: stream.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StreamIngestion_OpenStream_FullMethodName = "/embedai.v1.StreamIngestion/OpenStream"
)

// StreamIngestionClient is the client API for StreamIngestion service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamIngestionClient interface {
	OpenStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamFrame, StreamAck], error)
}

type streamIngestionClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamIngestionClient(cc grpc.ClientConnInterface) StreamIngestionClient {
	return &streamIngestionClient{cc}
}

func (c *streamIngestionClient) OpenStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamFrame, StreamAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StreamIngestion_ServiceDesc.Streams[0], StreamIngestion_OpenStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamFrame, StreamAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamIngestion_OpenStreamClient = grpc.BidiStreamingClient[StreamFrame, StreamAck]

// StreamIngestionServer is the server API for StreamIngestion service.
// All implementations must embed UnimplementedStreamIngestionServer
// for forward compatibility.
type StreamIngestionServer interface {
	OpenStream(grpc.BidiStreamingServer[StreamFrame, StreamAck]) error
	mustEmbedUnimplementedStreamIngestionServer()
}

// UnimplementedStreamIngestionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStreamIngestionServer struct{}

func (UnimplementedStreamIngestionServer) OpenStream(grpc.BidiStreamingServer[StreamFrame, StreamAck]) error {
	return status.Errorf(codes.Unimplemented, "method OpenStream not implemented")
}
func (UnimplementedStreamIngestionServer) mustEmbedUnimplementedStreamIngestionServer() {}
func (UnimplementedStreamIngestionServer) testEmbeddedByValue()                         {}

// UnsafeStreamIngestionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamIngestionServer will
// result in compilation errors.
type UnsafeStreamIngestionServer interface {
	mustEmbedUnimplementedStreamIngestionServer()
}

func RegisterStreamIngestionServer(s grpc.ServiceRegistrar, srv StreamIngestionServer) {
	// If the following call pancis, it indicates UnimplementedStreamIngestionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StreamIngestion_ServiceDesc, srv)
}

func _StreamIngestion_OpenStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamIngestionServer).OpenStream(&grpc.GenericServerStream[StreamFrame, StreamAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamIngestion_OpenStreamServer = grpc.BidiStreamingServer[StreamFrame, StreamAck]

// StreamIngestion_ServiceDesc is the grpc.ServiceDesc for StreamIngestion service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamIngestion_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "embedai.v1.StreamIngestion",
	HandlerType: (*StreamIngestionServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OpenStream",
			Handler:       _StreamIngestion_OpenStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "stream.proto",
}
