# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: episode.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'episode.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\repisode.proto\x12\nembedai.v1\"d\n\x14\x45pisodeIngestedEvent\x12\x12\n\nepisode_id\x18\x01 \x01(\t\x12\x12\n\nproject_id\x18\x02 \x01(\t\x12\x14\n\x0cstorage_path\x18\x03 \x01(\t\x12\x0e\n\x06\x66ormat\x18\x04 \x01(\t\"S\n\x11\x45pisodeReadyEvent\x12\x12\n\nepisode_id\x18\x01 \x01(\t\x12\x15\n\rquality_score\x18\x02 \x01(\x02\x12\x13\n\x0btopic_count\x18\x03 \x01(\x05\x42/Z-github.com/embedai/datahub/shared/proto;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'episode_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z-github.com/embedai/datahub/shared/proto;proto'
  _globals['_EPISODEINGESTEDEVENT']._serialized_start=29
  _globals['_EPISODEINGESTEDEVENT']._serialized_end=129
  _globals['_EPISODEREADYEVENT']._serialized_start=131
  _globals['_EPISODEREADYEVENT']._serialized_end=214
# @@protoc_insertion_point(module_scope)
