# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stream.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cstream.proto\x12\nembedai.v1\"\x9f\x01\n\x0bStreamFrame\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x12\n\nproject_id\x18\x02 \x01(\t\x12\x10\n\x08robot_id\x18\x03 \x01(\t\x12\x0f\n\x07seq_num\x18\x04 \x01(\x04\x12\x14\n\x0ctimestamp_ns\x18\x05 \x01(\x03\x12\r\n\x05topic\x18\x06 \x01(\t\x12\x0f\n\x07payload\x18\x07 \x01(\x0c\x12\x0f\n\x07is_last\x18\x08 \x01(\x08\"E\n\tStreamAck\x12\x14\n\x0clast_ack_seq\x18\x01 \x01(\x04\x12\x12\n\nepisode_id\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t2S\n\x0fStreamIngestion\x12@\n\nOpenStream\x12\x17.embedai.v1.StreamFrame\x1a\x15.embedai.v1.StreamAck(\x01\x30\x01\x42/Z-github.com/embedai/datahub/shared/proto;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z-github.com/embedai/datahub/shared/proto;proto'
  _globals['_STREAMFRAME']._serialized_start=29
  _globals['_STREAMFRAME']._serialized_end=188
  _globals['_STREAMACK']._serialized_start=190
  _globals['_STREAMACK']._serialized_end=259
  _globals['_STREAMINGESTION']._serialized_start=261
  _globals['_STREAMINGESTION']._serialized_end=344
# @@protoc_insertion_point(module_scope)
